version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd $CODEBUILD_SRC_DIR  # Use dynamic source directory
      - npm install

  build:
    commands:
      - echo "Starting the server..."
      - node app.js

artifacts:
  files:
    - '**/*'

