version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd backend
      - npm install

  build:
    commands:
      - echo "Starting the server..."
      - node server.js

artifacts:
  files:
    - '**/*'
  base-directory: backend
