version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install   # Install all dependencies from package.json
  pre_build:
    commands:
      - echo "Preparing build..."
  build:
    commands:
      - echo "Starting the server..."
      - node app.js &
  post_build:
    commands:
      - echo "Build complete."
artifacts:
  files:
    - '**/*'
