version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd cd /codebuild/output/src791908036/src/github.com/saba-2002/backend-demo-saba 
      - npm install

  build:
    commands:
      - echo "Starting the server..."
      - node app.js

artifacts:
  files:
    - '**/*'
  base-directory: backend-demo-saba
