version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo su ubuntu
      - cd backend-demo-saba
      - npm install

  build:
    commands:
      - echo "Starting the server..."
      - node app.js

artifacts:
  files:
    - '**/*'
  base-directory: backend-demo-saba
